### ISSUE TITLE
Standardize the asm syntax

### ISSUE THREAD

**Issue by Yamakaky** [techcompliant/TC-Specs#25]
Currently, there are a lot of different and incompatible syntax going around. It should be standardized.

I suggest reusing a subset of https://sourceware.org/binutils/docs/as/Pseudo-Ops.html plus the C preprocessor, simply because people are used to them. We don't have to invent yet another syntax.

**Comment by paultech** [comment]
Cross repo duplication of https://github.com/techcompliant/DASM/issues/13
