### ISSUE TITLE
Add a list of DCPU emulators

### ISSUE THREAD

**Issue by Yamakaky** [techcompliant/TC-Specs#27]
Maybe a wiki page, world-editable. It would also compare the features, like the devices supported, tick accuracy, instruction set...

**Comment by Yamakaky** [comment]
It could start by making the wiki world-writable

**Comment by paultech** [comment]
Well there is the slight matter of how TC as a game 'endorses' other emulators - A community list is of little benefit if the code ran in the emulator, does not meet the in-game emulator specifications resulting in confusion amongst the community.

In addition, TC emulator has lots of device specifications that require in-game simulation to produce meaningful results or an environment where DCPUs may be wired together - outside emulators become of less use in that case.

**Comment by Yamakaky** [comment]
This list would help seeing which compatibility level an emulator has with the spec.

**Comment by paultech** [comment]
We only support one offical emulator. This is not for discussion of DCPU-16 but of techcompliant the game.
