### ISSUE TITLE
Tick rate

### ISSUE THREAD

**Issue by Yamakaky** [techcompliant/TC-Specs#28]
I didn't find it standardized. Is it still 100_000?

**Comment by andyleap** [comment]
It's not standardized.  100khz is the default, but different computer models may have different rates.

**Comment by Yamakaky** [comment]
So you plan to have different computers in-game?

**Comment by andyleap** [comment]
Yes, we do.  If you want to learn more about Tech Compliant, our IRC (#techcompliant on freenode) or reddit (https://www.reddit.com/r/techcompliant/) are more appropriate places to ask questions.

**Comment by Yamakaky** [comment]
Yes, sorry.
