### ISSUE TITLE
Keyboard queue/stack behavior is undefined

### ISSUE THREAD

**Issue by azertyfun** [techcompliant/TC-Specs#29]
As-is, the official spec for the keyboard only says `Store next key from buffer to C register, or 0 if the buffer is empty`, but does not state wether keys are stored in a queue or a stack (FIFO vs LIFO), and does not state the length of the queue (though I guess that should be undefined because it is dependent on the model?).

@l3nn0x mentionned that notch's emulator used to be 16 keys FIFO, so there's that bit of info I guess.

**Comment by andyleap** [comment]
Current hardware is 8 item FIFO queue, updated the spec to match.

**Comment by Yamakaky** [comment]
LIFO would be strange ^^
