### ISSUE TITLE
IMVA - 4 or 8 bits per row?

### ISSUE THREAD

**Issue by orlof** [techcompliant/TC-Specs#38]
This is not an issue - just a discussion - feel free to close.

IMVA provides nice balance for both text and graphics applications.

Text apps will probably use it in 80 chars (LEM font) per row mode and would benefit if IMVA would split the words in 4 (instead of 8) pixel chunks to rows. For graphics apps this would not have much impact.

Should IMVA change from 8 to 4 bit chunks, or is this a deliberate design decision?

**Comment by paultech** [comment]
Just alerting original spec author @Meisaka

**Comment by Meisaka** [comment]
The 8 columns per chunk was quite deliberate, the design overall contrasts with the LEM in that the bit raster is mirrored and rotated from how the LEM does it's font style.
Other more direct considerations in the design were to allow a smooth scrolling appearance (assuming display is synced over a network) and the efficiency of drawing horizontal and vertical lines being somewhat simpler with the 8 column raster.
The display of 4x8 (LEM style) fonts requires few extra instructions over an 8x8 font, but I think it's worth it to leave that up to software as a significant memory saver, and to keep the display somewhat interesting to program for.

**Comment by orlof** [comment]
Thank you for the rationale. I think we can close this issue :)
