### ISSUE TITLE
dcpu behaviour with literal destination operand

### ISSUE THREAD

**Issue by wolfnether** [techcompliant/TC-Specs#45]
what is the behaviour of dcpu with literal on destination operand

**Comment by paultech** [comment]
A current pending-approval doc outlines features of the CPU better including literal usages:
https://github.com/shepheb/TC-Specs/blob/0e1ea0a5d011adbead2f683a50b46a10d91bd23b/CPU/DCPU.md

Let me know if that does not answer the question.

**Comment by wolfnether** [comment]
thanks

**Comment by paultech** [comment]
Unsure if you are aware  but we also publish the emulator we use internally so you are welcome to check complex questions against the source base:
https://github.com/techcompliant/GEMU
